# Generated by Django 6.0.3 on 2026-03-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_post_comment_story_follow_postlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="users.post",
            ),
        ),
    ]
